In [1]:
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.stats.mstats import gmean
from statistics import mean
from statistics import stdev, pstdev
import warnings
warnings.filterwarnings('ignore')

# Change the date_list to get the desired period
# Change the exchange_list to get the desired exchange

In [2]:
dates_11 = ['2011-01-31','2011-02-28','2011-03-31','2011-04-30','2011-05-31','2011-06-30','2011-07-31','2011-08-31','2011-09-30','2011-10-31','2011-11-30','2011-12-31']
dates_12 = ['2012-01-31','2012-02-29','2012-03-31','2012-04-30','2012-05-31','2012-06-30','2012-07-31','2012-08-31','2012-09-30','2012-10-31','2012-11-30','2012-12-31']
dates_13 = ['2013-01-31','2013-02-28','2013-03-31','2013-04-30','2013-05-31','2013-06-30','2013-07-31','2013-08-31','2013-09-30','2013-10-31','2013-11-30','2013-12-31']
dates_14 = ['2014-01-31','2014-02-28','2014-03-31','2014-04-30','2014-05-31','2014-06-30','2014-07-31','2014-08-31','2014-09-30','2014-10-31','2014-11-30','2014-12-31']
dates_15 = ['2015-01-31','2015-02-28','2015-03-31','2015-04-30','2015-05-31','2015-06-30','2015-07-31','2015-08-31','2015-09-30','2015-10-31','2015-11-30','2015-12-31']
dates_16 = ['2016-01-31','2016-02-29','2016-03-31','2016-04-30','2016-05-31','2016-06-30','2016-07-31','2016-08-31','2016-09-30','2016-10-31','2016-11-30','2016-12-31']
dates_17 = ['2017-01-31','2017-02-28','2017-03-31','2017-04-30','2017-05-31','2017-06-30','2017-07-31','2017-08-31','2017-09-30','2017-10-31','2017-11-30','2017-12-31']
dates_18 = ['2018-01-31','2018-02-28','2018-03-31','2018-04-30','2018-05-31','2018-06-30','2018-07-31','2018-08-31','2018-09-30','2018-10-31','2018-11-30','2018-12-31']
dates_19 = ['2019-01-31','2019-02-28','2019-03-31','2019-04-30','2019-05-31','2019-06-30','2019-07-31','2019-08-31','2019-09-30','2019-10-31','2019-11-30','2019-12-31']
dates_20 = ['2020-01-31','2020-02-29','2020-03-31','2020-04-30','2020-05-31','2020-06-30','2020-07-31','2020-08-31','2020-09-30','2020-10-31','2020-11-30','2020-12-31']
dates_21 = ['2021-01-31','2021-02-28','2021-03-31','2021-04-30','2021-05-31','2021-06-30','2021-07-31','2021-08-31','2021-09-30','2021-10-31','2021-11-30','2021-12-31']

In [3]:
FILE_PATH = "C:/Users/Farhan/Desktop/3 CSVs SQL Data/"
exchange_list = ["NasdaqGS"]
date_list = dates_11+dates_12+dates_13+dates_14+dates_15+dates_16+dates_17+dates_18+dates_19+dates_20+dates_21
# date_list = ['2020-11-30','2020-12-31','2021-01-31','2021-02-28']

In [4]:
data= []
df = pd.DataFrame()
for exchange in exchange_list:
    for date in date_list:
        file_name = FILE_PATH+exchange+"/"+exchange+"_"+date+".csv"
        tmp = pd.read_csv(file_name)
        data.append(tmp)
        df = pd.concat([df,tmp])
df = df.drop(['Unnamed: 0'], axis=1).reset_index()
#df = df.set_index(['tradingitemid','date']).sort_index()

# Mannual:
## 1. Decide whether to pre-define value of some raw-data like minority interest. (Too many NaN values for some stocks.
## 2ã€‚ Missing data: IQ_DA_SUPPL_CF (PMAN is computed without DEPI now), IQ_TBV, IQ_TOTAL_CL (No quarterly data -> No GP/Capital Avg)
## 3. Need to fetch daily price to calculate SMA, Price Volatility etc.

In [5]:
df['Change in CA']=df['IQ_TOTAL_CA-0']-df['IQ_TOTAL_CA-4']
df['Change in Cash']=df['IQ_CASH_INVEST-0']-df['IQ_CASH_INVEST-4']
df['Change in CL']=df['IQ_TOTAL_CL-0']-df['IQ_TOTAL_CL-4']
df['Change in LTD']=df['IQ_CURRENT_PORT_DEBT-0']-df['IQ_CURRENT_PORT_DEBT-4']
df['Change in Tax Payable']=df['IQ_INC_TAX_PAY_CURRENT-0']-df['IQ_INC_TAX_PAY_CURRENT-4']
df['STA'] = np.where(df[['Change in CA','Change in Cash','Change in CL','Change in LTD','Change in Tax Payable']].isnull().any(axis=1), 
                     np.nan, 
                     ((df['Change in CA']-df['Change in Cash'])-(df['Change in CL']-df['Change in LTD']-df['Change in Tax Payable'])-df["IQ_DA_CF-0"])/df["IQ_TOTAL_ASSETS-0"])


df['SNOA'] = np.where(df[['IQ_TOTAL_ASSETS-0','IQ_DA_CF-0','IQ_ST_DEBT-0','IQ_CURRENT_PORT_DEBT-0','IQ_LT_DEBT-0','IQ_MINORITY_INTEREST-0','IQ_PREF_EQUITY-0','IQ_TOTAL_COMMON_EQUITY-0']].isnull().any(axis=1), 
                     np.nan, 
                    ((df['IQ_TOTAL_ASSETS-0']-df['IQ_DA_CF-0'])-(df['IQ_TOTAL_ASSETS-0']-df['IQ_ST_DEBT-0']-df['IQ_CURRENT_PORT_DEBT-0']-df['IQ_LT_DEBT-0']\
                                                         -df['IQ_MINORITY_INTEREST-0']-df['IQ_PREF_EQUITY-0']-df['IQ_TOTAL_COMMON_EQUITY-0']))/df['IQ_TOTAL_ASSETS-0'])



df['DSRI']= np.where(df[['IQ_AR-0','IQ_TOTAL_REV-0','IQ_AR-4','IQ_TOTAL_REV-4']].isnull().any(axis=1), 
                     1, 
                    (df['IQ_AR-0']/df['IQ_TOTAL_REV-0'])/(df['IQ_AR-4']/df['IQ_TOTAL_REV-4']))

df['GMI'] = np.where(df[['IQ_GP-0','IQ_TOTAL_REV-0','IQ_GP-4','IQ_TOTAL_REV-4']].isnull().any(axis=1), 
                     1, 
                    (df['IQ_GP-4']/df['IQ_TOTAL_REV-4']) /(df['IQ_GP-0']/df['IQ_TOTAL_REV-0']))
df['AQI']= np.where(df[['IQ_TOTAL_CA-0','IQ_NPPE-0','IQ_LT_INVEST-0','IQ_TOTAL_ASSETS-0','IQ_TOTAL_CA-4','IQ_NPPE-4','IQ_LT_INVEST-4','IQ_TOTAL_ASSETS-4']].isnull().any(axis=1), 
                     1, 
                    (1-((df['IQ_TOTAL_CA-0']+df['IQ_NPPE-0']+df['IQ_LT_INVEST-0'])/df['IQ_TOTAL_ASSETS-0']))/(1-((df['IQ_TOTAL_CA-4']+df['IQ_NPPE-4']+df['IQ_LT_INVEST-4'])/df['IQ_TOTAL_ASSETS-4'])))
df['SGI']= np.where(df[['IQ_TOTAL_REV-0','IQ_TOTAL_REV-4']].isnull().any(axis=1), 
                     1, 
                    df['IQ_TOTAL_REV-0']/df['IQ_TOTAL_REV-4'])
# DEPI
df['SGAI']= np.where(df[['IQ_SGA_SUPPL-0','IQ_TOTAL_REV-0','IQ_SGA_SUPPL-4','IQ_TOTAL_REV-4']].isnull().any(axis=1), 
                     1, 
                    (df['IQ_SGA_SUPPL-0']/df['IQ_TOTAL_REV-0'])/(df['IQ_SGA_SUPPL-4']/df['IQ_TOTAL_REV-4']))
df['Leverage Ratio T']= np.where(df[['IQ_TOTAL_CL-0','IQ_LT_DEBT-0','IQ_TOTAL_ASSETS-0']].isnull().any(axis=1), 
                     np.nan, 
                    (df['IQ_TOTAL_CL-0']+df['IQ_LT_DEBT-0'])/(df['IQ_TOTAL_ASSETS-0']))
df['Leverage Ratio T-4']= np.where(df[['IQ_TOTAL_CL-4','IQ_LT_DEBT-4','IQ_TOTAL_ASSETS-4']].isnull().any(axis=1), 
                     np.nan, 
                    (df['IQ_TOTAL_CL-4']+df['IQ_LT_DEBT-4'])/(df['IQ_TOTAL_ASSETS-4']))
df['LVGI']= np.where(df[['Leverage Ratio T','Leverage Ratio T-4']].isnull().any(axis=1), 
                     1, 
                    (df['Leverage Ratio T'])/(df['Leverage Ratio T-4']))
df['TATA']= np.where(df[['IQ_NI-0','IQ_CASH_OPER-0','IQ_TOTAL_ASSETS-0']].isnull().any(axis=1), 
                     np.nan, 
                    (df['IQ_NI-0'] - df['IQ_CASH_OPER-0'])/df['IQ_TOTAL_ASSETS-0'])
df['PROBM Model'] = -4.84+df['DSRI']*0.92+df['GMI']*0.528+df['AQI']*0.404+ df['SGI']*0.892-df['SGAI']*0.172-df['LVGI']*0.327+df['TATA']*4.679
df['PROBM to PMAN'] = norm.cdf(df['PROBM Model'])

df['Altman Z'] =  df['IQ_Z_SCORE-0'].fillna(df['IQ_Z_SCORE-0_FY'])

#TBV

df['Net Debt/Total Common Equity'] = df['IQ_NET_DEBT-0']/df['IQ_TOTAL_COMMON_EQUITY-0']


df['IAR'] = df['IQ_GW_INTAN-0_FY']/df['IQ_TOTAL_ASSETS-0_FY']


df['ORECTA'] = (df['IQ_TOTAL_ASSETS-0']-df['IQ_CASH_ST_INVEST-0']-df['IQ_AR-0']-df['IQ_INVENTORY-0']-df['IQ_NPPE-0'])/df['IQ_TOTAL_ASSETS-0']

# Avg Rev/GP Growth 


df['GPTA'] = df['IQ_GP-0']/df['IQ_TOTAL_ASSETS-0']
df['GPTA-1'] = df['IQ_GP-1']/df['IQ_TOTAL_ASSETS-1']
df['GPTA-2'] = df['IQ_GP-2']/df['IQ_TOTAL_ASSETS-2']
df['GPTA-3'] = df['IQ_GP-3']/df['IQ_TOTAL_ASSETS-3']
df['GPTA Avg'] = (df['GPTA']+df['GPTA-1']+df['GPTA-2']+df['GPTA-3'])/4

#GP/Capital Avg

df['GPM']=df['IQ_GP-0_QTR']/df['IQ_TOTAL_REV-0_QTR']
df['GPM-1']=df['IQ_GP-1_QTR']/df['IQ_TOTAL_REV-1_QTR']
df['GPM-2']=df['IQ_GP-2_QTR']/df['IQ_TOTAL_REV-2_QTR']
df['GPM-3']=df['IQ_GP-3_QTR']/df['IQ_TOTAL_REV-3_QTR']
df['GPM-4']=df['IQ_GP-4_QTR']/df['IQ_TOTAL_REV-4_QTR']
df['GPM-5']=df['IQ_GP-5_QTR']/df['IQ_TOTAL_REV-5_QTR']
df['GPM-6']=df['IQ_GP-6_QTR']/df['IQ_TOTAL_REV-6_QTR']
df['GPM-7']=df['IQ_GP-7_QTR']/df['IQ_TOTAL_REV-7_QTR']
df['GPM-8']=df['IQ_GP-8_QTR']/df['IQ_TOTAL_REV-8_QTR'] 
df['Avg Margin Growth'] = np.where(df[['GPM','GPM-1','GPM-2','GPM-3','GPM-4','GPM-5','GPM-6','GPM-7','GPM-8']].isnull().any(axis=1), 
                          np.nan, 
                          gmean([df['GPM']/df['GPM-1'],df['GPM-1']/df['GPM-2'],df['GPM-2']/df['GPM-3'],df['GPM-3']/df['GPM-4'],
                                 df['GPM-4']/df['GPM-5'],df['GPM-5']/df['GPM-6'],df['GPM-6']/df['GPM-7'],df['GPM-7']/df['GPM-8']])-1)

df['Margin Stability'] = np.where(df[['GPM','GPM-1','GPM-2','GPM-3','GPM-4','GPM-5','GPM-6','GPM-7','GPM-8']].isnull().any(axis=1), 
                          np.nan, 
                          df[['GPM','GPM-1','GPM-2','GPM-3','GPM-4','GPM-5','GPM-6','GPM-7']].mean(axis = 1)/
                                 df[['GPM','GPM-1','GPM-2','GPM-3','GPM-4','GPM-5','GPM-6','GPM-7']].std(axis = 1))



df['EBITDA M']=df['IQ_EBIT-0_QTR']/df['IQ_TOTAL_REV-0_QTR']
df['EBITDA M-1']=df['IQ_EBIT-1_QTR']/df['IQ_TOTAL_REV-1_QTR']
df['EBITDA M-2']=df['IQ_EBIT-2_QTR']/df['IQ_TOTAL_REV-2_QTR']
df['EBITDA M-3']=df['IQ_EBIT-3_QTR']/df['IQ_TOTAL_REV-3_QTR']
df['EBITDA M-4']=df['IQ_EBIT-4_QTR']/df['IQ_TOTAL_REV-4_QTR']
df['EBITDA M-5']=df['IQ_EBIT-5_QTR']/df['IQ_TOTAL_REV-5_QTR']
df['EBITDA M-6']=df['IQ_EBIT-6_QTR']/df['IQ_TOTAL_REV-6_QTR']
df['EBITDA M-7']=df['IQ_EBIT-7_QTR']/df['IQ_TOTAL_REV-7_QTR']
df['EBITDA M-8']=df['IQ_EBIT-8_QTR']/df['IQ_TOTAL_REV-8_QTR'] 
df['Avg EBITDA Margin Growth'] = np.where(df[['EBITDA M','EBITDA M-1','EBITDA M-2','EBITDA M-3','EBITDA M-4','EBITDA M-5','EBITDA M-6','EBITDA M-7','EBITDA M-8']].isnull().any(axis=1), 
                          np.nan, 
                          gmean([df['EBITDA M']/df['EBITDA M-1'],df['EBITDA M-1']/df['EBITDA M-2'],df['EBITDA M-2']/df['EBITDA M-3'],df['EBITDA M-3']/df['EBITDA M-4'],
                                 df['EBITDA M-4']/df['EBITDA M-5'],df['EBITDA M-5']/df['EBITDA M-6'],df['EBITDA M-6']/df['EBITDA M-7'],df['EBITDA M-7']/df['EBITDA M-8']])-1)
df['EBITDA Margin Stability'] = np.where(df[['EBITDA M','EBITDA M-1','EBITDA M-2','EBITDA M-3','EBITDA M-4','EBITDA M-5','EBITDA M-6','EBITDA M-7','EBITDA M-8']].isnull().any(axis=1), 
                          np.nan, 
                          df[['EBITDA M','EBITDA M-1','EBITDA M-2','EBITDA M-3','EBITDA M-4','EBITDA M-5','EBITDA M-6','EBITDA M-7']].mean(axis = 1)/
                                 df[['EBITDA M','EBITDA M-1','EBITDA M-2','EBITDA M-3','EBITDA M-4','EBITDA M-5','EBITDA M-6','EBITDA M-7']].std(axis = 1))



df['EV/EBITDA'] =df['IQ_TEV']/ df['IQ_EBITDA-0']
df['EV/EBIT'] =df['IQ_TEV']/ df['IQ_EBIT-0']
df['EV'] = df['IQ_TEV']
df['GP'] = df['IQ_GP-0']
df['EV/GP'] = df['EV'] / df['GP']

df

,index,tradingitemid,tickersymbol,exchangeid,companyid,companyname,country,tradingitem_id,company_id,First Trade Date [Primary Listing],...,EBITDA M-6,EBITDA M-7,EBITDA M-8,Avg EBITDA Margin Growth,EBITDA Margin Stability,EV/EBITDA,EV/EBIT,EV,GP,EV/GP
0,0,2585893,AAON,458,320500,"AAON, Inc.",United States,2585893,320500,1991-01-03,...,0.162573,0.150360,0.160496,-0.042931,5.535922,9.595958,12.298805,423.939820,56.212000,7.541803
1,1,2586852,ATVI,458,24281,"Activision, Inc.",United States,2586852,24281,1985-05-07,...,0.210031,-0.198807,-0.177855,NaN,0.347662,14.628182,15.524200,8222.501215,1359.235000,6.049360
2,2,2586916,ACXM,458,24292,"LiveRamp Holdings, Inc.",United States,2586916,24292,1985-04-16,...,0.050172,0.139038,0.107695,-0.004885,3.580833,7.012847,13.782464,1615.346130,276.324000,5.845841
3,3,2587024,ADBE,458,24321,Adobe Inc.,United States,2587024,24321,1987-02-03,...,0.233987,0.279996,0.330625,-0.017594,8.641740,11.804540,15.204620,15453.063431,3396.498000,4.549705
4,4,2587051,ADTN,458,332752,"ADTRAN, Inc.",United States,2587051,332752,1994-08-10,...,0.215053,0.207504,0.191366,0.044605,7.624232,15.147947,16.186105,2490.458800,358.863000,6.939860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232843,1759,1685097019,TCBX,458,270611213,"Third Coast Bancshares, Inc.",United States,1685097019,270611213,2021-11-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.872723,NaN
232844,1760,1685654225,EXFY,458,59692786,"Expensify, Inc.",United States,1685654225,59692786,2021-11-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.821000,NaN
232845,1761,1687141649,FOSLL,458,317037,"Fossil Group, Inc.",United States,1687141649,317037,NaN,...,0.017969,0.026764,0.017946,NaN,-0.169276,7.830421,11.429547,912.580766,893.828000,1.020980
232846,1762,1672821289,RIVN,458,144746614,"Rivian Automotive, Inc.",United States,1672821289,144746614,2021-11-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232847,1763,1685510681,SEAT.W,458,53887479,Vivid Seats Inc.,United States,1685510681,53887479,NaN,...,NaN,NaN,NaN,NaN,NaN,-111.216812,-103.930076,1689.383378,107.255000,15.751092

In [6]:
df.to_csv("NasdaqGS.csv")